### ISSUE TITLE
请问后续会放出int8版本吗，vllm fp16 8卡A100显存不够

### ISSUE THREAD

**Issue by lishicheng1996** [Tencent/Tencent-Hunyuan-Large#12]
如题，请问后续有放出int8 量化版本的计划吗？或者有什么方法能在8卡A100上进行推理吗？
非常感谢🙏

**Comment by mayihehou** [comment]
已经放出了，我们的模型可以用int8进行推理，部署方式参见[int8-quantized-model-deployment](https://github.com/Tencent/Tencent-Hunyuan-Large?tab=readme-ov-file#int8-quantized-model-deployment)
模型请用[Hunyuan-A52B-Instruct](https://huggingface.co/tencent/Tencent-Hunyuan-Large/tree/main/Hunyuan-A52B-Instruct)

**Comment by lishicheng1996** [comment]
好的，非常感谢

**Comment by Maxhyl** [comment]
你好，请问8*A100 80G可以运行Int8模型吗？我测试了会出现OOM的情况
