### ISSUE TITLE
可以提供下Tencent-Hunyuan-Large模型在OCR Benchmark中的得分吗？

### ISSUE THREAD

**Issue by Mike575** [Tencent/Tencent-Hunyuan-Large#5]
可以提供下Tencent-Hunyuan-Large模型在OCR Benchmark中的得分吗？

**Comment by dickzhu2012** [comment]
你好，hunyuan-large是文生文模型，多模态模型会在后续陆续开源。
这里OCR模型是否是指多模态模型下的benchmark指标呢？

**Comment by Mike575** [comment]
> 你好，hunyuan-large是文生文模型，多模态模型会在后续陆续开源。 这里OCR模型是否是指多模态模型下的benchmark指标呢？

是的呢，这个OCR Benchmark 指的是 https://huggingface.co/spaces/echo840/ocrbench-leaderboard。

**Comment by dickzhu2012** [comment]
感谢支持，我们多模态模型也会在一些准备和完善后近期逐步放出来，谢谢关注
